FROM alpine

ENV DOLI_VERSION 8.0.3

RUN wget -q https://github.com/Dolibarr/dolibarr/archive/${DOLI_VERSION}.tar.gz \
 && tar xf ${DOLI_VERSION}.tar.gz \
 && mv dolibarr-${DOLI_VERSION}/htdocs . \
 && rm -rf dolibarr-${DOLI_VERSION} ${DOLI_VERSION}.tar.gz

FROM php:fpm-alpine

RUN apk --no-cache add postgresql-dev libpng-dev \
 && docker-php-ext-install gd pgsql zip

COPY --from=0 htdocs /var/www/html
RUN touch conf/conf.php && mkdir documents && chown www-data documents conf/conf.php
