FROM alpine

ENV DOLI_VERSION 8.0.3

RUN wget -q https://github.com/Dolibarr/dolibarr/archive/${DOLI_VERSION}.tar.gz \
 && tar xf ${DOLI_VERSION}.tar.gz \
 && mv dolibarr-${DOLI_VERSION}/htdocs . \
 && rm -rf dolibarr-${DOLI_VERSION} ${DOLI_VERSION}.tar.gz

FROM nginx:alpine

COPY --from=0 htdocs /var/www/html
ADD nginx.conf /etc/nginx/conf.d/default.conf
