version: '3'

networks:
  web:
    external: true

services:
  keycloak:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_ADDR=db
      - DB_VENDOR=postgres
      - KEYCLOAK_HOSTNAME=keycloak.${CHATONS_DOMAIN:-localhost}
      - PROXY_ADDRESS_FORWARDING=true
    expose:
      - "80"
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_SERVICE:-keycloak}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_SERVICE:-keycloak}.${CHATONS_DOMAIN:-localhost}"
    networks:
      default:
      web:
        aliases:
          - keycloak.${CHATONS_DOMAIN:-localhost}

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/keycloak/db:/var/lib/postgresql/data
